/**
 * Dotnet Api Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: change@me.ext
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Manufacturer } from './manufacturer';


export interface ManufacturersResponse { 
    results?: Array<Manufacturer>;
}

