import '@testing-library/jest-dom';
import { render } from '@testing-library/react';
import React from 'react';
import { ManufacturersResponse } from '../../../api/swagger/manufacturersResponse';
import { mockUseQuery } from '../../../test/setupTests';
import Manufacturer from './Manufacturer';
test('render Manufacturer ', () => {
    const mockManufacturerData: ManufacturersResponse = { results: [{ id: '2', name: 'manufacturer2' }] };
    mockUseQuery(mockManufacturerData);
    const component = render(<Manufacturer data={[]} />);
    expect(component).toBeTruthy();
    const manuBox = component.getByTestId('manufacturer-box');
    expect(manuBox).toBeTruthy();
    expect(manuBox).toBeInTheDocument();
    const button = component.getByRole('button');
    expect(button).toBeTruthy();
    expect(button).toBeVisible();
    const input = component.getByRole('textbox');
    expect(input).toBeTruthy();
    expect(input).toBeVisible();
    const label = component.getByTestId('manu-textfield');
    expect(label).toBeVisible();
    expect(label).toBeInTheDocument();
});
