url: 'https://pages.github.harrybin/react/'
markdown: kramdown
description: This coding guide describes additional best practices well as DOs and DON'Ts not covered by the project template it belongs to.
