name: Playwright Snapshot Tests

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]
  # Ensure this runs on Dependabot PRs
  pull_request_target:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]

# Limit concurrent runs per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # For pull_request_target, we need to checkout the PR head
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Build application
      run: npm run build
      
    - name: Run Playwright tests
      run: npx playwright test
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwrightTests/test-reports/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-screenshots
        path: test-results/
        retention-days: 30